<?php
if (!defined('BASEPATH'))
 	exit('No direct script access allowed');

$config['field'] = array(
   'simcard' => array(
      'phone_number' => 'Phone Number',
      'phone_number_type' => 'Type',
      'provider_id' => 'Provider',
      'active_period' => 'Active Period',
      'expired_date' => 'Expired Date',
      'nik' => 'NIK',
      'nkk' => 'NKK',
      'saldo' => 'Saldo',
      'status' => 'Status',
      'user_id' => 'PIC',
      'rak_id' => 'Rak',
      'created_date' => 'Created',
   ),
   'email' => array(
      'phone_number' => 'Phone Number',
      'phone_number_type' => 'Type',
      'email' => 'Email',
      'display_name' => 'Display Name',
      'password' => 'Password',
      'birth_day' => 'Birth Day',
      'status' => 'Status',
      'info' => 'Info',
      'user_id' => 'PIC',
      'created_date' => 'Created',
   ),
   'twitter' => array(
      'phone_number' => 'Phone Number',
      'display_name' => 'Display Name',
      'email' => 'Email',
      'screen_name' => 'Screen Name',
      'created_twitter' => 'Created Account',
      'birth_date' => 'Birth Date',
      'password' => 'Password',
      'cookies' => 'Cookies',
      'twitter_id' => 'Twitter ID',
      'followers' => 'followers',
      'apps_id' => 'Apps ID',
      'apps_name' => 'Apps Name',
      'consumer_key' => 'Consumer Key',
      'consumer_secret' => 'Consumer Secret',
      'access_token' => 'Access Token',
      'access_token_secret' => 'Access Token Secret',
      'status' => 'Status',
      'client_id' => 'Client',
      'client_id_key' => 'Client ID',
      'proxy_id' => 'Proxy',
      'proxy_id_key' => 'Proxy ID',
      'user_id' => 'PIC',
      'user_id_key' => 'PIC ID',
      'created_date' => 'Created',
   ),
   'facebook' => array(
      'phone_number' => 'Phone Number',
      'display_name' => 'Display Name',
      'url' => 'URL',
      'email' => 'Email',
      'created_facebook' => 'Created Account',
      'birth_date' => 'Birth Date',
      'facebook_id' => 'Facebook ID',
      'password' => 'Password',
      'cookies' => 'Cookies',
      'friends' => 'Friends',
      'info' => 'Info',
      'access_token' => 'Access Token',
      'status' => 'Status',
      'client_id' => 'Client',
      'client_id_key' => 'Client ID',
      'proxy_id' => 'Proxy',
      'proxy_id_key' => 'Proxy ID',
      'user_id' => 'PIC',
      'user_id_key' => 'PIC ID',
      'created_date' => 'Created',
   ),
   'instagram' => array(
      'phone_number' => 'Phone Number',
      'display_name' => 'Display Name',
      'username' => 'Username',
      'email' => 'Email',
      'created_instagram' => 'Created Account',
      'birth_date' => 'Birth Date',
      'password' => 'Password',
      'cookies' => 'Cookies',
      'followers' => 'Followers',
      'info' => 'Info',
      'status' => 'Status',
      'client_id' => 'Client',
      'client_id_key' => 'Client ID',
      'proxy_id' => 'Proxy',
      'proxy_id_key' => 'Proxy ID',
      'user_id' => 'PIC',
      'user_id_key' => 'PIC ID',
      'created_date' => 'Created',
   ),
   'proxy' => array(
      'id' => 'ID',
      'network' => 'Network',
      'ip_address' => 'IP Address',
      'port' => 'Port',
      'username' => 'Username',
      'password' => 'Password',
      'location' => 'Location',
      'status' => 'Status',
      'created_date' => 'Created Date',
      'user_id' => 'User ID',

   )
);
